name: Backstage CI workflow

on:
  workflow_call:
    inputs:
      VAULT_KV_PATH:
        required: false
        type: string
    secrets:
      NPM_REGISTRY_CREDENTIALS:
        required: true
      GH_TOKEN:
        required: false
      VAULT_INTERNAL_ADDR:
        required: true
      VAULT_TOKEN:
        required: true
      VPN_CONFIG:
        required: true
      VPN_PASS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Vault Cli
        uses: eLco/setup-vault@v1
        with:
          version: '~1.9.2'
      - name: Connect to VPN
        if: ${{ inputs.VAULT_KV_PATH }} != ''
        uses: munditrade/action-connect_vpn@main
        with:
          vpn_config: ${{ secrets.VPN_CONFIG }}
          vpn_pass: ${{ secrets.VPN_PASS }}
      - name: Vault Secrets to env
        if: ${{ inputs.VAULT_KV_PATH }} != ''
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: "vault kv get -format yaml -field=data ${{ inputs.VAULT_KV_PATH }}| sed 's/: /=/' > .env"
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.NPM_REGISTRY_CREDENTIALS }}'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Login to Artifact Registry
        run: pnpm artifactregistry-login
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Running lint rules
        run: pnpm lint
      - name: Running test
        run: pnpm test --passWithNoTests
      - name: Build changes
        run: pnpm build
