name: Reusable CI workflow

on:
  workflow_call:
    secrets:
      NPM_REGISTRY_CREDENTIALS:
        required: true
      NPM_TOKEN:
        required: false
      GH_TOKEN:
        required: false
      VPN_CONFIG:
        required: true
      VPN_PASS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: true
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Vault Cli
        uses: eLco/setup-vault@v1
        with:
          version: '~1.9.2'
      - name: Connect to VPN
        uses: munditrade/action-connect_vpn@main
        with:
          vpn_config: ${{ secrets.VPN_CONFIG }}
          vpn_pass: ${{ secrets.VPN_PASS }}
      - name: Vault Secrets to env
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: "vault kv get -format yaml -field=data ${{ inputs.VAULT_KV_PATH }}| sed 's/: /=/' > .env"
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.NPM_REGISTRY_CREDENTIALS }}'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm run lint
      - run: npm test -- --passWithNoTests